### PR TITLE
Update DynamicFieldITSMConfigItemAJAXHandler.pm

### PR DESCRIPTION
**Pull request by mo-azfar**
Fix for #3 
Tested on v6.0.30

### CODE REVIEW

**Comment by reneeb** [comment]
Thanks, I will review this PR this afternoon.

**Review by reneeb — CHANGES_REQUESTED** [review]
The .sopm ist generated based on the information in https://github.com/reneeb/otrs-DynamicFieldITSMConfigItem/blob/master/doc/DynamicFieldITSMConfigItem.json

So, please revert this change.

**Review by reneeb — CHANGES_REQUESTED** [review]
Please do not upload the .opm file.

**Comment by reneeb** [comment]
Thanks!

**Comment by mo-azfar** [comment]
Apologize. Accidentally push from my local machine

**Comment by reneeb** [comment]
No worries! I'm glad someone was working on the issue. Thanks!

**Comment by reneeb** [comment]
Thanks for the patch! A fixed version is uploaded to OPAR.

**Pull request merged**
